# Generated by Django 5.0.1 on 2024-02-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="phone",
            new_name="phonenumber",
        ),
    ]
