# Generated by Django 5.0.1 on 2024-02-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_rename_phone_contact_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("product_price", models.IntegerField()),
                ("product_desc", models.TextField(max_length=500)),
                ("product_category", models.CharField(default="", max_length=50)),
                ("product_subcategory", models.CharField(default="", max_length=50)),
                ("product_image", models.ImageField(upload_to="images/images")),
            ],
        ),
    ]
